---

- hosts: all
  tasks:
    - name: Not being evil and installing PHP JSON
      apt: name=php5-json state=present

    - name: Installing PHP Redis
      apt: name=php5-redis state=present

    - name: Installing PHP MCrypt
      apt: name=php5-mcrypt state=present

    - name: Enabling MCrypt module
      command: php5enmod mcrypt

  handlers:
    - name: Restart Avahi
      service: name=avahi-daemon state=restarted


- hosts: front
  tasks:
    - name: Installing PHP and Apache
      apt: name=libapache2-mod-php5 state=present

    - name: Allow www-data to see Vagrant files.
      action: user name=www-data groups=vagrant append=true

    - name: Copying redis config.
      copy: src=redis.conf dest=/etc/redis/ mode=0644

    - name: Installing Redis Server
      apt: name=redis-server state=present

    - name: Installing MySQL Server
      apt: name=mysql-server state=present

    - name: Installing PHP MySQL
      apt: name=php5-mysql state=present

    - name: Installing Python MySQL
      apt: name=python-mysqldb state=present

    - name: Creating MySQL Schema
      mysql_db: name=laravel201 state=present

    - name: Create our VirtualHost
      copy: src=laravel-201.conf dest=/etc/apache2/sites-available/ mode=0644

    - name: Disable the default VirtualHost
      command: a2dissite 000-default

    - name: Enable our VirtualHost
      command: a2ensite laravel-201
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted


- hosts: worker
  tasks:
    - name: Installing PHP5 CLI
      apt: name=php5-cli state=present

